### ISSUE TITLE
Improve readme with component features and examples

### ISSUE THREAD

**Issue by albertopaITX** [nomasystems/nimagefetch-ios#9]
Right now the readme contains a code snippet that doesn't compile.

My suggestion is to provide examples at least for:
1. use of the NImageFetchView
2. use of the lib using an UIImageView
3. cache/memory cleanup
4. task cancellation

Thanks

**Comment by albertopeam** [comment]
updated readme [pr](https://github.com/nomasystems/nimagefetch-ios/pull/10)
